import { createContext, useContext, useState, useCallback, type ReactNode } from 'react'

export type Language = 'en' | 'zh' | 'ja'

interface Translations {
  [key: string]: string
}

const translations: Record<Language, Translations> = {
  en: {
    'nav.guides': 'FEATURED',
    'nav.bosses': 'BOSSES',
    'nav.combat': 'COMBAT',
    'nav.community': 'COMMUNITY',
    'nav.playNow': 'PLAY NOW',
    'hero.label': 'GAME GUIDE',
    'hero.title': 'CRIMSON DESERT',
    'hero.subtitle': 'Master the sands of Pywel. Complete walkthroughs, boss strategies, and combat guides for Pearl Abyss\'s open-world epic.',
    'hero.cta.primary': 'EXPLORE GUIDES',
    'hero.cta.secondary': 'LATEST NEWS',
    'news.title': 'LATEST NEWS',
    'news.subtitle': 'Stay updated with the latest patches, events, and community highlights',
    'news.readMore': 'Read More',
    'categories.title': 'GUIDE CATEGORIES',
    'categories.subtitle': 'Everything you need to conquer Pywel',
    'categories.boss.title': 'Boss Strategies',
    'categories.boss.desc': 'Detailed phase-by-phase breakdowns for every campaign boss from Myurdin to Umbra, including \'watch and learn\' abilities and cheese spots.',
    'categories.combat.title': 'Combat Mastery',
    'categories.combat.desc': 'Master the art of parrying, grapple combos, and elemental abilities. Learn weapon switching, stagger mechanics, and optimal skill trees.',
    'categories.quest.title': 'Quest Walkthroughs',
    'categories.quest.desc': 'Complete step-by-step guides for every main story chapter, side quest, and hidden mission across all regions of Pywel.',
    'categories.explore.title': 'Exploration & Secrets',
    'categories.explore.desc': 'Abyss puzzle solutions, artifact locations, mount taming guides, cooking recipes, and hidden area walkthroughs.',
    'categories.articles': 'ARTICLES',
    'guides.title': 'FEATURED GUIDES',
    'guides.view': 'View Guide',
    'reviews.title': 'COMMUNITY REVIEWS',
    'reviews.subtitle': 'See what players are saying about Crimson Desert',
    'reviews.rate': 'Rate this game',
    'reviews.write': 'Write a Review',
    'reviews.name': 'Your Name',
    'reviews.review': 'Your Review',
    'reviews.submit': 'Submit Review',
    'reviews.thanks': 'Thank you for your review!',
    'combat.title': 'MASTER THE ART OF WAR',
    'combat.body': "From grappling and disarming enemies to wielding elemental Storm Veil and Flame Strike abilities, Crimson Desert's combat system rewards creativity and precision. Perfect parries, learn boss moves through the 'watch and learn' mechanic, and forge your path to becoming Pywel's greatest warrior.",
    'combat.cta': 'VIEW COMBAT GUIDES',
    'newsletter.title': 'JOIN THE GREYMANES',
    'newsletter.subtitle': 'Get weekly guides, boss strategies, and community updates delivered to your inbox.',
    'newsletter.placeholder': 'Enter your email',
    'newsletter.submit': 'SUBSCRIBE',
    'newsletter.thanks': 'Welcome to the Greymanes!',
    'footer.tagline': "The ultimate game guide for Pearl Abyss's open-world epic. Built by the community, for the community.",
    'footer.guides': 'GUIDES',
    'footer.boss': 'Boss Strategies',
    'footer.combat': 'Combat Guides',
    'footer.quests': 'Quest Walkthroughs',
    'footer.explore': 'Exploration',
    'footer.community': 'COMMUNITY',
    'footer.reviews': 'Reviews',
    'footer.forums': 'Forums',
    'footer.discord': 'Discord',
    'footer.submit': 'Submit Guide',
    'footer.resources': 'RESOURCES',
    'footer.patches': 'Patch Notes',
    'footer.tier': 'Tier Lists',
    'footer.map': 'Interactive Map',
    'footer.downloads': 'Downloads',
    'footer.about': 'ABOUT',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '2026 Crimson Desert Guide. Not affiliated with Pearl Abyss.',
    'ad.sponsored': 'Sponsored',
    'lang.en': 'English',
    'lang.zh': 'Chinese',
    'lang.ja': 'Japanese',
  },
  zh: {
    'nav.guides': 'GUIDES',
    'nav.bosses': 'Boss',
    'nav.combat': '战斗',
    'nav.community': 'COMMUNITY',
    'nav.playNow': '立即游玩',
    'hero.label': '游戏GUIDES',
    'hero.title': '红色沙漠',
    'hero.subtitle': '征服皮维尔大陆的完整GUIDES。包含全Boss Strategies、COMBAT GUIDES和Pearl Abyss开放世界史诗的详细流程。',
    'hero.cta.primary': '浏览GUIDES',
    'hero.cta.secondary': 'LATEST NEWS',
    'news.title': 'LATEST NEWS',
    'news.subtitle': 'Stay updated with patches, events & community',
    'news.readMore': '阅读更多',
    'categories.title': 'GUIDES分类',
    'categories.subtitle': 'Everything you need to conquer Pywel',
    'categories.boss.title': 'Boss Strategies',
    'categories.boss.desc': '从缪尔丁到翁布拉的每个剧情Boss的详细阶段GUIDES，包含"观察学习"技能和tips点位。',
    'categories.combat.title': 'Combat Mastery',
    'categories.combat.desc': '精通格挡、擒抱连击和元素技能。学习武器切换、失衡机制和最优技能树。',
    'categories.quest.title': 'Quest Walkthroughs',
    'categories.quest.desc': '皮维尔大陆所有区域的主线sections、支线任务和隐藏任务的完整逐步指南。',
    'categories.explore.title': 'Exploration & Secrets',
    'categories.explore.desc': '深渊谜题解法、神器位置、坐骑驯服指南、烹饪配方和隐藏区域GUIDES。',
    'categories.articles': ' ARTICLES',
    'guides.title': '精选GUIDES',
    'guides.view': '查看GUIDES',
    'reviews.title': '玩家评价',
    'reviews.subtitle': 'See what players are saying about Crimson Desert',
    'reviews.rate': 'Rating',
    'reviews.write': 'Write a Review',
    'reviews.name': 'Your Name',
    'reviews.review': 'Your Review',
    'reviews.submit': 'Submit Review',
    'reviews.thanks': '感谢Your Review！',
    'combat.title': 'MASTER THE ART OF WAR',
    'combat.body': "从擒抱和缴械敌人到运用元素风暴面纱和火焰打击技能，红色沙漠的战斗系统奖励创造力和精准度。通过\"观察学习\"机制掌握完美格挡，学习Boss招式，铸就你成为皮维尔最伟大战士的道路。",
    'combat.cta': '查看COMBAT GUIDES',
    'newsletter.title': 'JOIN THE GREYMANES',
    'newsletter.subtitle': '每周GUIDES、Boss Strategies和COMMUNITY更新直达你的邮箱。',
    'newsletter.placeholder': 'Enter your email',
    'newsletter.submit': 'SUBSCRIBE',
    'newsletter.thanks': '欢迎JOIN THE GREYMANES！',
    'footer.tagline': 'Pearl Abyss开放世界史诗的终极游戏指南。由COMMUNITY构建，为COMMUNITY服务。',
    'footer.guides': 'GUIDES',
    'footer.boss': 'Boss Strategies',
    'footer.combat': 'COMBAT GUIDES',
    'footer.quests': 'Quest Walkthroughs',
    'footer.explore': '探索',
    'footer.community': 'COMMUNITY',
    'footer.reviews': '评价',
    'footer.forums': 'Forums',
    'footer.discord': 'Discord',
    'footer.submit': '提交GUIDES',
    'footer.resources': 'RESOURCES',
    'footer.patches': 'Patch Notes',
    'footer.tier': 'Tier Lists',
    'footer.map': 'Interactive Map',
    'footer.downloads': 'Downloads',
    'footer.about': 'ABOUT',
    'footer.aboutUs': 'ABOUT我们',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '2026 红色沙漠GUIDES。与Pearl Abyss无关。',
    'ad.sponsored': 'AD',
    'lang.en': '英文',
    'lang.zh': '中文',
    'lang.ja': '日文',
  },
  ja: {
    'nav.guides': 'ガイド',
    'nav.bosses': 'ボス',
    'nav.combat': '戦闘',
    'nav.community': 'コミュニティ',
    'nav.playNow': '今すぐプレイ',
    'hero.label': 'ゲームガイド',
    'hero.title': 'クリムゾンデザート',
    'hero.subtitle': 'ピウェルの砂を制覇せよ。完全GUIDES、ボス戦略、そしてPearl Abyssのオープンワールド大作の戦闘ガイド。',
    'hero.cta.primary': 'ガイドを探す',
    'hero.cta.secondary': '最新ニュース',
    'news.title': '最新ニュース',
    'news.subtitle': '最新のパッチ、イベント、コミュニティのハイライトをチェック',
    'news.readMore': '続きを読む',
    'categories.title': 'ガイドカテゴリー',
    'categories.subtitle': 'ピウェルを征服するために必要なすべて',
    'categories.boss.title': 'ボス戦略',
    'categories.boss.desc': 'ミュルディンからアンブラまで、すべてのキャンペーンボスの詳細なフェーズ別GUIDES。「見て学ぶ」アビリティとチーズポイントも解説。',
    'categories.combat.title': '戦闘マスタリー',
    'categories.combat.desc': 'パリィ、グラップルコンボ、エレメンタルアビリティの極意を学ぶ。武器切り替え、スタッガーメカニクス、最適なスキルツリーをマスター。',
    'categories.quest.title': 'クエストGUIDES',
    'categories.quest.desc': 'ピウェルのすべての地域にあるメインストーリー章、サイドクエスト、隠しミッションの完全なステップバイステップガイド。',
    'categories.explore.title': '探索と秘密',
    'categories.explore.desc': 'アビスパズルの解法、アーティファクトの場所、マウントテイミングガイド、料理レシピ、隠しエリアのGUIDES。',
    'categories.articles': '記事',
    'guides.title': 'おすすめガイド',
    'guides.view': 'ガイドを見る',
    'reviews.title': 'コミュニティレビュー',
    'reviews.subtitle': 'プレイヤーがクリムゾンデザートについてどう感じているか見てみよう',
    'reviews.rate': '評価する',
    'reviews.write': 'レビューを書く',
    'reviews.name': '名前',
    'reviews.review': 'レビュー',
    'reviews.submit': 'レビューを投稿',
    'reviews.thanks': 'レビューありがとうございます！',
    'combat.title': '戦いの艺术を極める',
    'combat.body': "敵を組み敷き武装解除する技から、エレメンタル・ストームヴェールとフレイムストライクのアビリティを振るうまで、クリムゾンデザートの戦闘システムは創造性と精度を報いる。パーフェクトパリィを極め、「見て学ぶ」メカニクスでボスの動きを学び、ピウェル最高の戦士への道を切り開こう。",
    'combat.cta': '戦闘ガイドを見る',
    'newsletter.title': 'グレイメインに参加',
    'newsletter.subtitle': '毎週のガイド、ボス戦略、コミュニティ更新をメールでお届け。',
    'newsletter.placeholder': 'メールアドレスを入力',
    'newsletter.submit': '購読',
    'newsletter.thanks': 'グレイメインへようこそ！',
    'footer.tagline': 'Pearl Abyssのオープンワールド大作の究極ゲームガイド。コミュニティによって、コミュニティのために構築。',
    'footer.guides': 'ガイド',
    'footer.boss': 'ボス戦略',
    'footer.combat': '戦闘ガイド',
    'footer.quests': 'クエストGUIDES',
    'footer.explore': '探索',
    'footer.community': 'コミュニティ',
    'footer.reviews': 'レビュー',
    'footer.forums': 'フォーラム',
    'footer.discord': 'Discord',
    'footer.submit': 'ガイドを投稿',
    'footer.resources': 'リソース',
    'footer.patches': 'パッチノート',
    'footer.tier': 'ティアリスト',
    'footer.map': 'インタラクティブマップ',
    'footer.downloads': 'ダウンロード',
    'footer.about': '概要',
    'footer.aboutUs': '私たちについて',
    'footer.contact': 'お問い合わせ',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.copyright': '2026 クリムゾンデザートガイド。Pearl Abyssとは無関係。',
    'ad.sponsored': '広告',
    'lang.en': '英語',
    'lang.zh': '中国語',
    'lang.ja': '日本語',
  }
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang)
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : lang === 'ja' ? 'ja' : 'en'
  }, [])

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations['en'][key] || key
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
